project_name: gowebly
report_sizes: true

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: default
    ldflags:
      - -s -w
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

upx:
  - ids: [default]
    enabled: true
    compress: best
    lzma: true
    brute: true
    goos: [linux, windows] # skip darwin (macOS 13.x Ventura is not supported now)
    goarch: [amd64, arm64]

release:
  ids: [default]
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  mode: replace
  header: |
    ## {{ if eq .Patch "0" }}✨{{ else }}⚙️{{ end }} The Gowebly CLI `{{ .Tag }}` {{ if eq .Patch "0" }}release{{ else }}patch{{ end }}

    {{- if eq .Patch "0" }}<img width="100%" alt="gowebly banner with logo" src="https://raw.githubusercontent.com/gowebly/.github/main/images/gowebly-project-banner.svg"/>

    A next-generation CLI tool to easily build amazing web applications with **Go** on the backend, using **htmx**, **hyperscript** or **Alpine.js** and the most popular **CSS frameworks** on the frontend.

    ## In this release

    ...{{ end }}
  footer: |
    ## How to update?

    For native Go installation (any platforms):

    ```console
    go install github.com/gowebly/gowebly/v2@latest
    ```

    For [Homebrew][brew_url] users (GNU/Linux, Apple macOS):

    ```console
    brew upgrade gowebly/tap/gowebly
    ```

    For other ways (any platforms): manually download and re-install a ready-made package from the `Assets` section.

    > 💡 Note: See the [Complete user guide][gowebly_url] to get a general information.

    ## Your help to improve project

    I invite you to participate in this project! Let's work **together** to create and popularize the **most useful** tool for developers on the web today.

    - Add [Issue][repo_issues_url] to ask questions and submit your features;
    - Make [Pull request][repo_pull_request_url] to send your improvements to the current codebase;
    - Create [Discussion][repo_discussions_url] to discuss and share your ideas;
    - Share the project link to your friends and family on [X (Twitter)][x_share_url], [Telegram][telegram_share_url], [WhatsApp][whatsapp_share_url], [Reddit][reddit_share_url];
    - Say a few words about the project on your social networks and blogs ([Dev.to][dev_to_url], [Medium][medium_url], [Хабр][habr_url], and so on);

    Your PRs, issues & any words are welcome! Thank you 😘

    <!-- Links -->

    [repo_issues_url]: https://github.com/gowebly/gowebly/issues
    [repo_pull_request_url]: https://github.com/gowebly/gowebly/pulls
    [repo_discussions_url]: https://github.com/gowebly/gowebly/discussions
    [brew_url]: https://brew.sh
    [gowebly_url]: https://gowebly.org
    [dev_to_url]: https://dev.to
    [medium_url]: https://medium.com
    [habr_url]: https://habr.com
    [x_share_url]: https://x.com/intent/tweet?hashtags=gowebly%2Cgo%2Chtmx&text=A%20next-generation%20CLI%20tool%20to%20easily%20build%20amazing%20web%20applications%20with%20Go%20on%20the%20backend%2C%20using%20htmx%20%26%20hyperscript%20and%20the%20most%20popular%20CSS%20frameworks%20on%20the%20frontend.&url=https%3A%2F%2Fgowebly.org
    [telegram_share_url]: https://t.me/share/url?text=A%20next-generation%20CLI%20tool%20to%20easily%20build%20amazing%20web%20applications%20with%20Go%20on%20the%20backend%2C%20using%20htmx%20%26%20hyperscript%20and%20the%20most%20popular%20CSS%20frameworks%20on%20the%20frontend.%20%23gowebly%20%23go%20%23htmx&url=https%3A%2F%2Fgowebly.org
    [whatsapp_share_url]: https://api.whatsapp.com/send?text=A%20next-generation%20CLI%20tool%20to%20easily%20build%20amazing%20web%20applications%20with%20Go%20on%20the%20backend%2C%20using%20htmx%20%26%20hyperscript%20and%20the%20most%20popular%20CSS%20frameworks%20on%20the%20frontend.%20https%3A%2F%2Fgowebly.org
    [reddit_share_url]: https://www.reddit.com/submit?title=A%20next-generation%20CLI%20tool%20to%20easily%20build%20amazing%20web%20applications%20with%20Go%20on%20the%20backend%2C%20using%20htmx%20%26%20hyperscript%20and%20the%20most%20popular%20CSS%20frameworks%20on%20the%20frontend.%20%23gowebly%20%23go%20%23htmx&url=https%3A%2F%2Fgowebly.org
  disable: false
  skip_upload: false

brews:
  - repository:
      owner: gowebly
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
    commit_author:
      name: Vic Shóstak
      email: koddr.me@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    caveats: |
      After install the Gowebly CLI, create a new project:

      $ gowebly create

      💡 Note: See the Complete user guide (https://gowebly.org/) to get a general information.
    homepage: "https://github.com/gowebly/{{ .ProjectName }}"
    description: |
      A next-generation CLI tool that makes it easy to create amazing web applications with Go on the backend, using htmx, hyperscript or Alpine.js and the most popular CSS frameworks on the frontend.
    license: Apache 2.0
    skip_upload: false

nfpms:
  - maintainer: Vic Shóstak <koddr.me@gmail.com>
    description: |
      A next-generation CLI tool that makes it easy to create amazing web applications with Go on the backend, using htmx, hyperscript or Alpine.js and the most popular CSS frameworks on the frontend.
    homepage: "https://github.com/gowebly/{{ .ProjectName }}"
    license: Apache 2.0
    formats: [deb, rpm, apk, archlinux]

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files: [LICENSE, README.md]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude: ["^*.md", "^*.ya?ml"]
  groups:
    - title: New features
      regexp: ^.*?((A|a)dd)|((N|n)ew)|((F|f)eature).*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Delete unused or stale
      regexp: ^.*?((D|d)elete)|((U|u)nused)|((S|s)tale).*?$
      order: 5
    - title: Others
      order: 999
