// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/gowebly/gowebly/internal/attachments"
	"github.com/gowebly/gowebly/internal/config"
	"github.com/gowebly/gowebly/internal/injectors"
)

// Injectors from wire.go:

// inject provides dependency injection process by the "google/wire" package.
func inject() (*injectors.Injector, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	files := attachments.New()
	injector, err := injectors.New(configConfig, files)
	if err != nil {
		return nil, err
	}
	return injector, nil
}
