// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/gowebly/gowebly/v3/internal/attachments"
	"github.com/gowebly/gowebly/v3/internal/config"
	"github.com/gowebly/gowebly/v3/internal/injectors"
)

// Injectors from wire.go:

// Inject provides the dependency injection process by the "google/wire" package.
func Inject() (*injectors.Injector, error) {
	configConfig := config.New()
	attachmentsAttachments := attachments.New()
	injector, err := injectors.New(configConfig, attachmentsAttachments)
	if err != nil {
		return nil, err
	}
	return injector, nil
}
